# Generated by Django 6.0.5 on 2026-05-23 07:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlyworkspace',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='monthlyworkspace',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asiancam_workspaces_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='monthlyworkspace',
            name='rejected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='monthlyworkspace',
            name='rejected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asiancam_workspaces_rejected', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='monthlyworkspace',
            name='review_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='monthlyworkspace',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='monthlyworkspace',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asiancam_workspaces_submitted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='monthlyworkspace',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('waiting_customer', 'Waiting Customer'), ('completed', 'Completed / Waiting Approval'), ('approved', 'Approved'), ('rejected', 'Rejected / Return to Staff')], default='pending', max_length=30),
        ),
    ]
