# Generated by Django 6.0.5 on 2026-07-10 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0002_monthlyworkspace_approved_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlyworkspace',
            name='month',
            field=models.PositiveIntegerField(default=7),
        ),
    ]
