# Generated by Django 6.0.5 on 2026-05-16 16:16

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0003_accountingentry_accountingentryline'),
        ('core', '0003_alter_company_options_userprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_brands', to='core.company')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('company', 'name')},
            },
        ),
        migrations.CreateModel(
            name='ItemGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('code', models.CharField(blank=True, max_length=50)),
                ('memo', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_groups', to='core.company')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('company', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=80)),
                ('name', models.CharField(max_length=180)),
                ('item_type', models.CharField(choices=[('stock_part', 'Stock Part'), ('stock_assemble', 'Stock Assemble'), ('service', 'Service'), ('package', 'Package')], default='stock_part', max_length=30)),
                ('cost_price', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('sale_price', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('memo', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('cogs_account', models.ForeignKey(blank=True, help_text='Usually Cost of Goods Sold account', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cogs_items', to='accounting.chartofaccount')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_items', to='core.company')),
                ('inventory_account', models.ForeignKey(blank=True, help_text='Usually Inventory Asset account', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_items', to='accounting.chartofaccount')),
                ('revenue_account', models.ForeignKey(blank=True, help_text='Usually Sales Revenue account', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revenue_items', to='accounting.chartofaccount')),
                ('item_brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stock.itembrand')),
                ('item_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stock.itemgroup')),
            ],
            options={
                'ordering': ['code', 'name'],
            },
        ),
        migrations.CreateModel(
            name='StockDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('issue', 'Stock Issue'), ('adjustment', 'Stock Adjustment'), ('assembly', 'Stock Assembly'), ('transfer', 'Stock Transfer')], max_length=30)),
                ('number', models.CharField(blank=True, max_length=80)),
                ('document_date', models.DateField(default=django.utils.timezone.localdate)),
                ('memo', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('posted', 'Posted'), ('void', 'Void')], default='posted', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_documents', to='core.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('credit_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_credit_documents', to='accounting.chartofaccount')),
                ('debit_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_debit_documents', to='accounting.chartofaccount')),
                ('journal_entry', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_document', to='accounting.journalentry')),
            ],
            options={
                'ordering': ['-document_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='StockDocumentLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('memo', models.CharField(blank=True, max_length=255)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='stock.stockdocument')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_lines', to='stock.item')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='UnitSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('base_unit', models.CharField(default='pcs', max_length=50)),
                ('default_purchase', models.CharField(default='pcs', max_length=50)),
                ('default_sale', models.CharField(default='pcs', max_length=50)),
                ('memo', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit_sets', to='core.company')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('company', 'name')},
            },
        ),
        migrations.AddField(
            model_name='item',
            name='unit_set',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stock.unitset'),
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('code', models.CharField(blank=True, max_length=50)),
                ('memo', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouses', to='core.company')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('company', 'name')},
            },
        ),
        migrations.AddField(
            model_name='stockdocument',
            name='from_warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_transfers_from', to='stock.warehouse'),
        ),
        migrations.AddField(
            model_name='stockdocument',
            name='to_warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_transfers_to', to='stock.warehouse'),
        ),
        migrations.AddField(
            model_name='stockdocument',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_docs', to='stock.warehouse'),
        ),
        migrations.AlterUniqueTogether(
            name='item',
            unique_together={('company', 'code')},
        ),
    ]
