# Generated by Django 6.0.5 on 2026-05-16 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='vatin',
            field=models.CharField(blank=True, max_length=100, verbose_name='VATIN / Tax ID'),
        ),
    ]
