from .models import ChartOfAccount


SAMPLE_ACCOUNTS = [
    # Assets
    {
        "code": "1000",
        "name": "Assets",
        "local_name": "ទ្រព្យសកម្ម",
        "account_type": "asset",
        "report_type": "balance_sheet",
        "report_section": "Assets",
        "normal_balance": "debit",
        "is_group": True,
        "parent": None,
        "description": "All company assets.",
    },
    {
        "code": "1100",
        "name": "Current Assets",
        "local_name": "ទ្រព្យសកម្មរយៈពេលខ្លី",
        "account_type": "asset",
        "report_type": "balance_sheet",
        "report_section": "Current Asset",
        "normal_balance": "debit",
        "is_group": True,
        "parent": "1000",
        "description": "Cash, bank, receivable, inventory, and short-term assets.",
    },
    {
        "code": "1110",
        "name": "Cash on Hand",
        "local_name": "សាច់ប្រាក់ក្នុងដៃ",
        "account_type": "asset",
        "report_type": "balance_sheet",
        "report_section": "Current Asset",
        "normal_balance": "debit",
        "is_group": False,
        "parent": "1100",
        "description": "Cash kept in office or cashier.",
    },
    {
        "code": "1120",
        "name": "Cash in Bank",
        "local_name": "សាច់ប្រាក់នៅធនាគារ",
        "account_type": "asset",
        "report_type": "balance_sheet",
        "report_section": "Current Asset",
        "normal_balance": "debit",
        "is_group": False,
        "parent": "1100",
        "description": "Money deposited in bank accounts.",
    },
    {
        "code": "1130",
        "name": "Accounts Receivable",
        "local_name": "គណនីត្រូវទទួល",
        "account_type": "asset",
        "report_type": "balance_sheet",
        "report_section": "Current Asset",
        "normal_balance": "debit",
        "is_group": False,
        "parent": "1100",
        "description": "Money customers owe to the company.",
    },
    {
        "code": "1140",
        "name": "Inventory",
        "local_name": "សន្និធិ",
        "account_type": "asset",
        "report_type": "balance_sheet",
        "report_section": "Current Asset",
        "normal_balance": "debit",
        "is_group": False,
        "parent": "1100",
        "description": "Goods or stock for sale.",
    },
    {
        "code": "1150",
        "name": "Prepaid Expenses",
        "local_name": "ចំណាយបង់មុន",
        "account_type": "asset",
        "report_type": "balance_sheet",
        "report_section": "Current Asset",
        "normal_balance": "debit",
        "is_group": False,
        "parent": "1100",
        "description": "Expenses paid in advance.",
    },
    {
        "code": "1200",
        "name": "Fixed Assets",
        "local_name": "ទ្រព្យសកម្មថេរ",
        "account_type": "asset",
        "report_type": "balance_sheet",
        "report_section": "Fixed Asset",
        "normal_balance": "debit",
        "is_group": True,
        "parent": "1000",
        "description": "Long-term assets.",
    },
    {
        "code": "1210",
        "name": "Office Equipment",
        "local_name": "ឧបករណ៍ការិយាល័យ",
        "account_type": "asset",
        "report_type": "balance_sheet",
        "report_section": "Fixed Asset",
        "normal_balance": "debit",
        "is_group": False,
        "parent": "1200",
        "description": "Office equipment and computers.",
    },
    {
        "code": "1220",
        "name": "Accumulated Depreciation",
        "local_name": "រំលស់បង្គរ",
        "account_type": "asset",
        "report_type": "balance_sheet",
        "report_section": "Fixed Asset",
        "normal_balance": "credit",
        "is_group": False,
        "parent": "1200",
        "description": "Accumulated depreciation of fixed assets.",
    },

    # Liabilities
    {
        "code": "2000",
        "name": "Liabilities",
        "local_name": "បំណុល",
        "account_type": "liability",
        "report_type": "balance_sheet",
        "report_section": "Liabilities",
        "normal_balance": "credit",
        "is_group": True,
        "parent": None,
        "description": "All company liabilities.",
    },
    {
        "code": "2100",
        "name": "Current Liabilities",
        "local_name": "បំណុលរយៈពេលខ្លី",
        "account_type": "liability",
        "report_type": "balance_sheet",
        "report_section": "Current Liability",
        "normal_balance": "credit",
        "is_group": True,
        "parent": "2000",
        "description": "Short-term liabilities.",
    },
    {
        "code": "2110",
        "name": "Accounts Payable",
        "local_name": "គណនីត្រូវបង់",
        "account_type": "liability",
        "report_type": "balance_sheet",
        "report_section": "Current Liability",
        "normal_balance": "credit",
        "is_group": False,
        "parent": "2100",
        "description": "Money owed to suppliers.",
    },
    {
        "code": "2120",
        "name": "Salary Payable",
        "local_name": "ប្រាក់ខែត្រូវបង់",
        "account_type": "liability",
        "report_type": "balance_sheet",
        "report_section": "Current Liability",
        "normal_balance": "credit",
        "is_group": False,
        "parent": "2100",
        "description": "Salary and wages payable.",
    },
    {
        "code": "2130",
        "name": "Tax Payable",
        "local_name": "ពន្ធត្រូវបង់",
        "account_type": "liability",
        "report_type": "balance_sheet",
        "report_section": "Current Liability",
        "normal_balance": "credit",
        "is_group": False,
        "parent": "2100",
        "description": "Tax owed to government.",
    },
    {
        "code": "2140",
        "name": "VAT Payable",
        "local_name": "អាករលើតម្លៃបន្ថែមត្រូវបង់",
        "account_type": "liability",
        "report_type": "balance_sheet",
        "report_section": "Current Liability",
        "normal_balance": "credit",
        "is_group": False,
        "parent": "2100",
        "description": "VAT payable.",
    },
    {
        "code": "2200",
        "name": "Loan Payable",
        "local_name": "ប្រាក់កម្ចីត្រូវបង់",
        "account_type": "liability",
        "report_type": "balance_sheet",
        "report_section": "Non-current Liability",
        "normal_balance": "credit",
        "is_group": False,
        "parent": "2000",
        "description": "Bank or owner loans.",
    },

    # Equity
    {
        "code": "3000",
        "name": "Equity",
        "local_name": "មូលធន",
        "account_type": "equity",
        "report_type": "balance_sheet",
        "report_section": "Equity",
        "normal_balance": "credit",
        "is_group": True,
        "parent": None,
        "description": "Owner equity.",
    },
    {
        "code": "3100",
        "name": "Owner Capital",
        "local_name": "មូលធនម្ចាស់",
        "account_type": "equity",
        "report_type": "balance_sheet",
        "report_section": "Equity",
        "normal_balance": "credit",
        "is_group": False,
        "parent": "3000",
        "description": "Owner investment.",
    },
    {
        "code": "3200",
        "name": "Retained Earnings",
        "local_name": "ប្រាក់ចំណេញរក្សាទុក",
        "account_type": "equity",
        "report_type": "balance_sheet",
        "report_section": "Equity",
        "normal_balance": "credit",
        "is_group": False,
        "parent": "3000",
        "description": "Accumulated profit retained in business.",
    },

    # Revenue
    {
        "code": "4000",
        "name": "Revenue",
        "local_name": "ចំណូល",
        "account_type": "revenue",
        "report_type": "profit_loss",
        "report_section": "Revenue",
        "normal_balance": "credit",
        "is_group": True,
        "parent": None,
        "description": "All revenue.",
    },
    {
        "code": "4100",
        "name": "Sales Revenue",
        "local_name": "ចំណូលពីការលក់",
        "account_type": "revenue",
        "report_type": "profit_loss",
        "report_section": "Revenue",
        "normal_balance": "credit",
        "is_group": False,
        "parent": "4000",
        "description": "Sales revenue from products or services.",
    },
    {
        "code": "4200",
        "name": "Service Revenue",
        "local_name": "ចំណូលសេវាកម្ម",
        "account_type": "revenue",
        "report_type": "profit_loss",
        "report_section": "Revenue",
        "normal_balance": "credit",
        "is_group": False,
        "parent": "4000",
        "description": "Service income.",
    },

    # Cost of Goods Sold
    {
        "code": "5000",
        "name": "Cost of Goods Sold",
        "local_name": "ថ្លៃដើមទំនិញលក់",
        "account_type": "cogs",
        "report_type": "profit_loss",
        "report_section": "Cost of Goods Sold",
        "normal_balance": "debit",
        "is_group": True,
        "parent": None,
        "description": "Direct cost of goods sold.",
    },
    {
        "code": "5100",
        "name": "Purchase Cost",
        "local_name": "ថ្លៃដើមទិញ",
        "account_type": "cogs",
        "report_type": "profit_loss",
        "report_section": "Cost of Goods Sold",
        "normal_balance": "debit",
        "is_group": False,
        "parent": "5000",
        "description": "Cost of purchased goods sold.",
    },

    # Expenses
    {
        "code": "6000",
        "name": "Expenses",
        "local_name": "ចំណាយ",
        "account_type": "expense",
        "report_type": "profit_loss",
        "report_section": "Expense",
        "normal_balance": "debit",
        "is_group": True,
        "parent": None,
        "description": "Operating expenses.",
    },
    {
        "code": "6100",
        "name": "Rent Expense",
        "local_name": "ចំណាយជួល",
        "account_type": "expense",
        "report_type": "profit_loss",
        "report_section": "Expense",
        "normal_balance": "debit",
        "is_group": False,
        "parent": "6000",
        "description": "Office or shop rent.",
    },
    {
        "code": "6200",
        "name": "Salary Expense",
        "local_name": "ចំណាយប្រាក់ខែ",
        "account_type": "expense",
        "report_type": "profit_loss",
        "report_section": "Expense",
        "normal_balance": "debit",
        "is_group": False,
        "parent": "6000",
        "description": "Salary and wages expense.",
    },
    {
        "code": "6300",
        "name": "Utilities Expense",
        "local_name": "ចំណាយទឹកភ្លើង",
        "account_type": "expense",
        "report_type": "profit_loss",
        "report_section": "Expense",
        "normal_balance": "debit",
        "is_group": False,
        "parent": "6000",
        "description": "Electricity, water, internet, and utilities.",
    },
    {
        "code": "6400",
        "name": "Office Supplies Expense",
        "local_name": "ចំណាយសម្ភារៈការិយាល័យ",
        "account_type": "expense",
        "report_type": "profit_loss",
        "report_section": "Expense",
        "normal_balance": "debit",
        "is_group": False,
        "parent": "6000",
        "description": "Office supplies and small expenses.",
    },
    {
        "code": "6500",
        "name": "Marketing Expense",
        "local_name": "ចំណាយទីផ្សារ",
        "account_type": "expense",
        "report_type": "profit_loss",
        "report_section": "Expense",
        "normal_balance": "debit",
        "is_group": False,
        "parent": "6000",
        "description": "Advertising and marketing expenses.",
    },
    {
        "code": "6600",
        "name": "Depreciation Expense",
        "local_name": "ចំណាយរំលស់",
        "account_type": "expense",
        "report_type": "profit_loss",
        "report_section": "Expense",
        "normal_balance": "debit",
        "is_group": False,
        "parent": "6000",
        "description": "Depreciation expense.",
    },

    # Other Income / Expense
    {
        "code": "7000",
        "name": "Other Income",
        "local_name": "ចំណូលផ្សេងៗ",
        "account_type": "other_income",
        "report_type": "profit_loss",
        "report_section": "Other Income",
        "normal_balance": "credit",
        "is_group": True,
        "parent": None,
        "description": "Other income.",
    },
    {
        "code": "7100",
        "name": "Interest Income",
        "local_name": "ចំណូលការប្រាក់",
        "account_type": "other_income",
        "report_type": "profit_loss",
        "report_section": "Other Income",
        "normal_balance": "credit",
        "is_group": False,
        "parent": "7000",
        "description": "Interest income.",
    },
    {
        "code": "8000",
        "name": "Other Expense",
        "local_name": "ចំណាយផ្សេងៗ",
        "account_type": "other_expense",
        "report_type": "profit_loss",
        "report_section": "Other Expense",
        "normal_balance": "debit",
        "is_group": True,
        "parent": None,
        "description": "Other expense.",
    },
    {
        "code": "8100",
        "name": "Bank Charge",
        "local_name": "ចំណាយសេវាធនាគារ",
        "account_type": "other_expense",
        "report_type": "profit_loss",
        "report_section": "Other Expense",
        "normal_balance": "debit",
        "is_group": False,
        "parent": "8000",
        "description": "Bank fees and charges.",
    },
]


def create_sample_coa(company):
    created_count = 0
    account_map = {}

    for data in SAMPLE_ACCOUNTS:
        parent_code = data.pop("parent")

        account, created = ChartOfAccount.objects.get_or_create(
            company=company,
            code=data["code"],
            defaults={
                **data,
                "parent": None,
            },
        )

        if created:
            created_count += 1

        account_map[account.code] = account

        data["parent"] = parent_code

    for data in SAMPLE_ACCOUNTS:
        parent_code = data["parent"]

        if parent_code:
            account = account_map.get(data["code"])
            parent = account_map.get(parent_code)

            if account and parent and account.parent_id != parent.id:
                account.parent = parent
                account.save(update_fields=["parent"])

    return created_count