# Generated by Django 6.0.5 on 2026-05-16 08:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('client_code', models.CharField(blank=True, max_length=50, unique=True)),
                ('tax_id', models.CharField(blank=True, max_length=100)),
                ('industry', models.CharField(blank=True, max_length=120)),
                ('contact_name', models.CharField(blank=True, max_length=150)),
                ('contact_phone', models.CharField(blank=True, max_length=80)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('paused', 'Paused')], default='active', max_length=20)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asiancam_clients_created', to=settings.AUTH_USER_MODEL)),
                ('customer_user', models.ForeignKey(blank=True, help_text='Customer login user for this client.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asiancam_client_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['company_name'],
            },
        ),
    ]
