import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

class Migration(migrations.Migration):
    dependencies=[('accounting','0004_bulkimportlog_accountcustomer_accountitem'),('vendors','0002_purchase_bill_workflow'),migrations.swappable_dependency(settings.AUTH_USER_MODEL)]
    operations=[
        migrations.CreateModel(name='VendorPayment',fields=[
            ('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('payment_date',models.DateField(default=django.utils.timezone.localdate)),('number',models.CharField(blank=True,max_length=80)),('payment_method',models.CharField(blank=True,default='Cash',max_length=80)),('currency',models.CharField(default='USD',max_length=20)),('memo',models.TextField(blank=True)),('total_amount',models.DecimalField(decimal_places=2,default=0,max_digits=14)),('status',models.CharField(choices=[('draft','Draft'),('posted','Posted'),('void','Void')],default='posted',max_length=20)),('created_at',models.DateTimeField(auto_now_add=True)),
            ('accounts_payable_account',models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name='vendor_payment_ap_accounts',to='accounting.chartofaccount')),('company',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='vendor_payments',to='core.company')),('created_by',models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,to=settings.AUTH_USER_MODEL)),('journal_entry',models.OneToOneField(blank=True,null=True,on_delete=django.db.models.deletion.SET_NULL,related_name='vendor_payment',to='accounting.journalentry')),('payment_account',models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name='vendor_payment_cash_accounts',to='accounting.chartofaccount')),('vendor',models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name='payments',to='vendors.vendor')),
        ],options={'ordering':['-payment_date','-id']}),
        migrations.CreateModel(name='VendorPaymentAllocation',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('discount',models.DecimalField(decimal_places=2,default=0,max_digits=14)),('amount',models.DecimalField(decimal_places=2,default=0,max_digits=14)),('memo',models.CharField(blank=True,max_length=255)),('bill',models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name='payment_allocations',to='vendors.purchasebill')),('payment',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='allocations',to='vendors.vendorpayment'))]),
        migrations.CreateModel(name='VendorPaymentOtherCharge',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('memo',models.CharField(max_length=255)),('amount',models.DecimalField(decimal_places=2,default=0,max_digits=14)),('account',models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name='vendor_payment_other_charges',to='accounting.chartofaccount')),('payment',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='other_charges',to='vendors.vendorpayment'))]),
    ]
