# Generated by Django 6.0.5 on 2026-10-01 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0005_vendorpaymentothercharge_tax_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendortransaction',
            name='transaction_type',
            field=models.CharField(choices=[('purchase_order', 'Purchase Order / Bill (Legacy)'), ('cash_expense', 'Cash Expense'), ('vendor_payment', 'Vendor Payment'), ('adjustment', 'Adjustment')], max_length=30),
        ),
    ]
