# Generated by Django 6.0.5 on 2026-10-02 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0006_alter_vendortransaction_transaction_type'),
        ('vendors', '0006_purchase_bill_line_tax_code'),
    ]

    operations = [
    ]
