# Generated by Django 6.0.5 on 2026-10-02 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0007_merge_20261001_1813'),
        ('vendors', '0007_merge_20261002_1734'),
    ]

    operations = [
    ]
