# Generated by Django 6.0.5 on 2026-05-17 01:35

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0003_accountingentry_accountingentryline'),
        ('core', '0003_alter_company_options_userprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('bank_name', models.CharField(blank=True, max_length=150)),
                ('account_number', models.CharField(blank=True, max_length=100)),
                ('currency', models.CharField(default='USD', max_length=20)),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('memo', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('chart_account', models.ForeignKey(help_text='Cash/Bank account in Chart of Accounts', on_delete=django.db.models.deletion.PROTECT, related_name='bank_accounts', to='accounting.chartofaccount')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to='core.company')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('company', 'name')},
            },
        ),
        migrations.CreateModel(
            name='BankDeposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deposit_date', models.DateField(default=django.utils.timezone.localdate)),
                ('number', models.CharField(blank=True, max_length=80)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('memo', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('posted', 'Posted'), ('void', 'Void')], default='posted', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_deposits', to='core.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('deposit_to', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deposits', to='accounting_ops.bankaccount')),
                ('journal_entry', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_deposit', to='accounting.journalentry')),
                ('source_account', models.ForeignKey(help_text='Usually Undeposited Funds, Cash on Hand, A/R, or clearing account', on_delete=django.db.models.deletion.PROTECT, related_name='bank_deposit_source_lines', to='accounting.chartofaccount')),
            ],
            options={
                'ordering': ['-deposit_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='BankReconcile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reconcile_date', models.DateField(default=django.utils.timezone.localdate)),
                ('tran_date', models.DateField(blank=True, null=True)),
                ('bank_balance', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('book_balance', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('difference', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('memo', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reconciles', to='accounting_ops.bankaccount')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_reconciles', to='core.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-reconcile_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='BankRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('priority_order', models.PositiveIntegerField(default=1)),
                ('money_direction', models.CharField(choices=[('in', 'Money In'), ('out', 'Money Out')], default='in', max_length=10)),
                ('keyword', models.CharField(blank=True, max_length=180)),
                ('memo', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_rules', to='core.company')),
                ('target_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bank_rules', to='accounting.chartofaccount')),
            ],
            options={
                'ordering': ['priority_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ImportHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('import_type', models.CharField(choices=[('stock_balance', 'Import Stock Balance'), ('item', 'Import Item'), ('vendor', 'Import Vendor'), ('customer', 'Import Customer'), ('chart_of_account', 'Import Chart of Account'), ('batch_transaction', 'Batch Transaction')], max_length=40)),
                ('file', models.FileField(blank=True, null=True, upload_to='accounting_imports/')),
                ('total_rows', models.PositiveIntegerField(default=0)),
                ('success_rows', models.PositiveIntegerField(default=0)),
                ('error_rows', models.PositiveIntegerField(default=0)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_histories', to='core.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LandedCostAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocation_date', models.DateField(default=django.utils.timezone.localdate)),
                ('number', models.CharField(blank=True, max_length=80)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('bill_no', models.CharField(blank=True, max_length=80)),
                ('vendor_name', models.CharField(blank=True, max_length=180)),
                ('po_number', models.CharField(blank=True, max_length=80)),
                ('allocation_method', models.CharField(choices=[('amount', 'By Amount'), ('qty', 'By Quantity'), ('weight', 'By Weight')], default='amount', max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('memo', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('posted', 'Posted'), ('void', 'Void')], default='posted', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('clearing_account', models.ForeignKey(help_text='Usually Freight/Clearing/AP', on_delete=django.db.models.deletion.PROTECT, related_name='landed_cost_credits', to='accounting.chartofaccount')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='landed_cost_allocations', to='core.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('journal_entry', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='landed_cost_allocation', to='accounting.journalentry')),
                ('landed_cost_account', models.ForeignKey(help_text='Usually Inventory Asset', on_delete=django.db.models.deletion.PROTECT, related_name='landed_cost_debits', to='accounting.chartofaccount')),
            ],
            options={
                'ordering': ['-allocation_date', '-id'],
            },
        ),
    ]
