# Generated by Django 6.0.5 on 2026-05-22 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting_ops', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importhistory',
            name='import_type',
            field=models.CharField(choices=[('stock_balance', 'Import Stock Balance'), ('item', 'Import Item'), ('vendor', 'Import Vendor'), ('customer', 'Import Customer'), ('chart_of_account', 'Import Chart of Account'), ('batch_transaction', 'Batch Transaction'), ('trial_balance', 'Trial Balance Full'), ('journal_opening', 'Journal Opening Balance'), ('outstanding_ap', 'Outstanding AP'), ('outstanding_ar', 'Outstanding AR')], max_length=40),
        ),
    ]
