# Generated by Django 6.0.5 on 2026-05-16 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_alter_company_options_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChartOfAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=200)),
                ('local_name', models.CharField(blank=True, max_length=200)),
                ('account_type', models.CharField(choices=[('asset', 'Asset'), ('liability', 'Liability'), ('equity', 'Equity'), ('revenue', 'Revenue'), ('cogs', 'Cost of Goods Sold'), ('expense', 'Expense'), ('other_income', 'Other Income'), ('other_expense', 'Other Expense')], max_length=30)),
                ('report_type', models.CharField(choices=[('balance_sheet', 'Balance Sheet'), ('profit_loss', 'Profit & Loss'), ('cash_flow', 'Cash Flow'), ('trial_balance', 'Trial Balance')], max_length=30)),
                ('report_section', models.CharField(blank=True, help_text='Example: Current Asset, Current Liability, Revenue, Expense', max_length=100)),
                ('normal_balance', models.CharField(choices=[('debit', 'Debit'), ('credit', 'Credit')], default='debit', max_length=10)),
                ('is_group', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chart_accounts', to='core.company')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='accounting.chartofaccount')),
            ],
            options={
                'verbose_name': 'Chart of Account',
                'verbose_name_plural': 'Chart of Accounts',
                'ordering': ['code', 'name'],
                'unique_together': {('company', 'code')},
            },
        ),
    ]
